### PR TITLE
Add support for More Block's Stairs Plus extension

### PR DESCRIPTION
**Pull request by RQWorldblender**
Also change a few node properties:

- Pyrite ore: make it appear in the creative inventory
- Pyrite block: change its sounds to metal

### CODE REVIEW

**Comment by Napiophelios** [comment]
I don't use the moreblocks mod, but shouldn't this call for "get_modpath("moreblocks")" instead of "stairsplus",
or does it matter?

**Comment by RQWorldblender** [comment]
It is possible to separate stairsplus from moreblocks, so that's why I state the former instead of the latter.

**Comment by Napiophelios** [comment]
which should I put in the depends file? Both mods as soft depends, yeah?

**Comment by RQWorldblender** [comment]
Just put 'moreblocks?', since stairsplus will most likely be bundled with moreblocks on every download.

**Pull request merged**
